// Code generated by ifacemaker; DO NOT EDIT.

package kubernetes

import (
	"context"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	storagev1 "k8s.io/api/storage/v1"
	apiextv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/rest"
	ctrlclient "sigs.k8s.io/controller-runtime/pkg/client"

	backupv1alpha1 "github.com/openeverest/openeverest/v2/api/backup/v1alpha1"
	"github.com/openeverest/openeverest/v2/api/core/v1alpha1"
	monitoringv1alpha1 "github.com/openeverest/openeverest/v2/api/monitoring/v1alpha1"
	"github.com/openeverest/openeverest/v2/pkg/accounts"
	"github.com/openeverest/openeverest/v2/pkg/common"
)

// KubernetesConnector ...
type KubernetesConnector interface {
	// Accounts returns an implementation of the accounts interface that
	// manages everest accounts directly via ConfigMaps.
	Accounts() accounts.Interface
	// ListBackupStorages returns list of backup storages in a given namespace.
	ListBackupStorages(ctx context.Context, opts ...ctrlclient.ListOption) (*backupv1alpha1.BackupStorageList, error)
	// GetBackupStorage returns a backup storage by name and namespace.
	GetBackupStorage(ctx context.Context, key ctrlclient.ObjectKey) (*backupv1alpha1.BackupStorage, error)
	// CreateBackupStorage creates a backup storage.
	CreateBackupStorage(ctx context.Context, storage *backupv1alpha1.BackupStorage) (*backupv1alpha1.BackupStorage, error)
	// UpdateBackupStorage updates a backup storage.
	UpdateBackupStorage(ctx context.Context, storage *backupv1alpha1.BackupStorage) (*backupv1alpha1.BackupStorage, error)
	// DeleteBackupStorage deletes a backup storage.
	DeleteBackupStorage(ctx context.Context, obj *backupv1alpha1.BackupStorage) error
	// GetBackup returns backup that matches the criteria.
	GetBackup(ctx context.Context, key ctrlclient.ObjectKey) (*backupv1alpha1.Backup, error)
	// DeleteBackup deletes backup that matches the criteria.
	DeleteBackup(ctx context.Context, obj *backupv1alpha1.Backup) error
	// CreateBackup creates backup.
	CreateBackup(ctx context.Context, backup *backupv1alpha1.Backup) (*backupv1alpha1.Backup, error)
	// UpdateBackup updates backup.
	UpdateBackup(ctx context.Context, backup *backupv1alpha1.Backup) (*backupv1alpha1.Backup, error)
	// ListBackupClasses returns list of backup classes that match the criteria.
	ListBackupClasses(ctx context.Context, opts ...ctrlclient.ListOption) (*backupv1alpha1.BackupClassList, error)
	// GetBackupClass returns backup class that matches the criteria.
	GetBackupClass(ctx context.Context, key ctrlclient.ObjectKey) (*backupv1alpha1.BackupClass, error)
	// GetConfigMap returns k8s configmap that matches the criteria.
	GetConfigMap(ctx context.Context, key ctrlclient.ObjectKey) (*corev1.ConfigMap, error)
	// CreateConfigMap creates k8s configmap.
	CreateConfigMap(ctx context.Context, config *corev1.ConfigMap) (*corev1.ConfigMap, error)
	// UpdateConfigMap updates k8s configmap.
	UpdateConfigMap(ctx context.Context, config *corev1.ConfigMap) (*corev1.ConfigMap, error)
	// ListCRDs lists all CRDs that match the criteria.
	ListCRDs(ctx context.Context, opts ...ctrlclient.ListOption) (*apiextv1.CustomResourceDefinitionList, error)
	// DeleteCRD deletes a CRD that matches the criteria.
	DeleteCRD(ctx context.Context, obj *apiextv1.CustomResourceDefinition) error
	// GetDeployment returns k8s deployment that matches the criteria.
	GetDeployment(ctx context.Context, key ctrlclient.ObjectKey) (*appsv1.Deployment, error)
	// UpdateDeployment updates a deployment and returns the updated object.
	UpdateDeployment(ctx context.Context, deployment *appsv1.Deployment) (*appsv1.Deployment, error)
	// ListDeployments returns a list of deployments that match the criteria.
	// This method returns a list of full objects (meta and spec).
	ListDeployments(ctx context.Context, opts ...ctrlclient.ListOption) (*appsv1.DeploymentList, error)
	// DeleteDeployment deletes a deployment that matches the criteria.
	DeleteDeployment(ctx context.Context, obj *appsv1.Deployment) error
	// RestartDeployment restarts deployment that matches the criteria.
	RestartDeployment(ctx context.Context, key ctrlclient.ObjectKey) error
	// WaitForRollout waits for rollout of deployment that matches the criteria.
	WaitForRollout(ctx context.Context, key ctrlclient.ObjectKey) error
	// ListInstanceBackups returns backups for the specified instance.
	ListInstanceBackups(ctx context.Context, namespace, instance string) (*backupv1alpha1.BackupList, error)
	// ListInstanceRestores returns restores performed for the specified instance.
	ListInstanceRestores(ctx context.Context, namespace, instance string) (*backupv1alpha1.RestoreList, error)
	// GetRestore returns a specific restore by namespaced name.
	GetRestore(ctx context.Context, key ctrlclient.ObjectKey) (*backupv1alpha1.Restore, error)
	// CreateRestore creates a new restore.
	CreateRestore(ctx context.Context, restore *backupv1alpha1.Restore) (*backupv1alpha1.Restore, error)
	// DeleteRestore deletes a restore.
	DeleteRestore(ctx context.Context, obj *backupv1alpha1.Restore) error
	// Kubeconfig returns the path to the kubeconfig.
	// This value is available only if the client was created with New() function.
	Kubeconfig() string
	// Config returns *rest.Config.
	Config() *rest.Config
	// WithKubernetesClient sets the k8s client.
	WithKubernetesClient(c ctrlclient.Client) *Kubernetes
	// Namespace returns the namespace OpenEverest is installed.
	Namespace() string
	// GetEverestID returns the ID of the namespace where everest is deployed.
	GetEverestID(ctx context.Context) (string, error)
	// GetClusterType tries to guess the underlying kubernetes cluster based on storage class.
	GetClusterType(ctx context.Context) (ClusterType, error)
	// ListMonitoringConfigsV2 returns list of managed monitoring configs that match the criteria.
	// This method returns a list of full objects (meta and spec).
	//
	// TODO Rename it to ListMonitoringConfigs once v1 code is removed.
	ListMonitoringConfigsV2(ctx context.Context, opts ...ctrlclient.ListOption) (*monitoringv1alpha1.MonitoringConfigList, error)
	// GetMonitoringConfigV2 returns monitoring config(full object) that matches the criteria.
	//
	// TODO Rename it to GetMonitoringConfig once v1 code is removed.
	GetMonitoringConfigV2(ctx context.Context, key ctrlclient.ObjectKey) (*monitoringv1alpha1.MonitoringConfig, error)
	// GetMonitoringConfigMetaV2 returns monitoring config(metadata only) that matches the criteria.
	//
	// TODO Rename it to GetMonitoringConfigMeta once v1 code is removed.
	GetMonitoringConfigMetaV2(ctx context.Context, key ctrlclient.ObjectKey) (*metav1.PartialObjectMetadata, error)
	// CreateMonitoringConfigV2 creates monitoring config.
	//
	// TODO Rename it to CreateMonitoringConfig once v1 code is removed.
	CreateMonitoringConfigV2(ctx context.Context, config *monitoringv1alpha1.MonitoringConfig) (*monitoringv1alpha1.MonitoringConfig, error)
	// UpdateMonitoringConfigV2 updates monitoring config.
	//
	// TODO Rename it to UpdateMonitoringConfig once v1 code is removed.
	UpdateMonitoringConfigV2(ctx context.Context, config *monitoringv1alpha1.MonitoringConfig) (*monitoringv1alpha1.MonitoringConfig, error)
	// DeleteMonitoringConfigV2 deletes monitoring config that matches the criteria.
	//
	// TODO Rename it to DeleteMonitoringConfig once v1 code is removed.
	DeleteMonitoringConfigV2(ctx context.Context, obj *monitoringv1alpha1.MonitoringConfig) error
	// CreateNamespace creates the given namespace.
	CreateNamespace(ctx context.Context, namespace *corev1.Namespace) (*corev1.Namespace, error)
	// GetNamespace returns a namespace that matches the criteria.
	GetNamespace(ctx context.Context, key ctrlclient.ObjectKey) (*corev1.Namespace, error)
	// GetDBNamespaces returns a list of DB namespaces that managed by the Everest and match the criteria.
	GetDBNamespaces(ctx context.Context, opts ...ctrlclient.ListOption) (*corev1.NamespaceList, error)
	// DeleteNamespace deletes a namespace that matches the criteria.
	DeleteNamespace(ctx context.Context, obj *corev1.Namespace) error
	// ListNamespaces lists all namespaces that match the criteria.
	// This method returns a list of full objects (meta and spec).
	ListNamespaces(ctx context.Context, opts ...ctrlclient.ListOption) (*corev1.NamespaceList, error)
	// UpdateNamespace updates the given namespace.
	UpdateNamespace(ctx context.Context, namespace *corev1.Namespace) (*corev1.Namespace, error)
	// ApplyManifestFile accepts manifest file contents, parses into []runtime.Object
	// and applies them against the cluster.
	ApplyManifestFile(ctx context.Context, fileBytes []byte, namespace string, ignoreObjects ...ctrlclient.Object) error
	// ApplyObject applies object.
	ApplyObject(obj runtime.Object) error
	// CreateRSAKeyPair creates a new RSA key pair and stores it in a secret.
	CreateRSAKeyPair(ctx context.Context) error
	// UpdateEverestSettings accepts the full list of Everest settings and updates the settings.
	UpdateEverestSettings(ctx context.Context, settings common.EverestSettings) error
	// GetEverestSettings returns Everest settings.
	GetEverestSettings(ctx context.Context) (common.EverestSettings, error)
	// GetAllClusterResources goes through all cluster nodes and sums their allocatable resources.
	GetAllClusterResources(ctx context.Context, clusterType ClusterType, volumes *corev1.PersistentVolumeList) (uint64, uint64, uint64, error)
	// GetConsumedCPUAndMemory returns consumed CPU and Memory in given namespace. If namespace
	// is empty, it tries to get them from all namespaces.
	GetConsumedCPUAndMemory(ctx context.Context, namespace string) (cpuMillis uint64, memoryBytes uint64, err error)
	// GetConsumedDiskBytes returns consumed bytes. The strategy differs based on k8s cluster type.
	GetConsumedDiskBytes(_ context.Context, clusterType ClusterType, volumes *corev1.PersistentVolumeList) (uint64, error)
	// ListSecrets returns list of secrets that match the criteria.
	// This method returns a list of full objects (meta and spec).
	ListSecrets(ctx context.Context, opts ...ctrlclient.ListOption) (*corev1.SecretList, error)
	// GetSecret returns a secret that matches the criteria.
	GetSecret(ctx context.Context, key ctrlclient.ObjectKey) (*corev1.Secret, error)
	// CreateSecret creates a secret.
	CreateSecret(ctx context.Context, secret *corev1.Secret) (*corev1.Secret, error)
	// UpdateSecret updates a secret.
	UpdateSecret(ctx context.Context, secret *corev1.Secret) (*corev1.Secret, error)
	// DeleteSecret deletes a secret that matches the criteria.
	DeleteSecret(ctx context.Context, obj *corev1.Secret) error
	// GetService returns service that matches the criteria.
	GetService(ctx context.Context, key ctrlclient.ObjectKey) (*corev1.Service, error)
	// ListPersistentVolumes returns list of persistent volumes that match the criteria.
	// This method returns a list of full objects (meta and spec).
	ListPersistentVolumes(ctx context.Context, opts ...ctrlclient.ListOption) (*corev1.PersistentVolumeList, error)
	// ListStorageClasses returns list of storage classes that match the criteria.
	// This method returns a list of full objects (meta and spec).
	ListStorageClasses(ctx context.Context, opts ...ctrlclient.ListOption) (*storagev1.StorageClassList, error)
	// ListPods returns list of pods that match the criteria.
	// This method returns a list of full objects (meta and spec).
	ListPods(ctx context.Context, opts ...ctrlclient.ListOption) (*corev1.PodList, error)
	// ListProviders returns list of providers that match the criteria.
	ListProviders(ctx context.Context, opts ...ctrlclient.ListOption) (*v1alpha1.ProviderList, error)
	// GetProvider returns provider that matches the criteria.
	GetProvider(ctx context.Context, key ctrlclient.ObjectKey) (*v1alpha1.Provider, error)
	// ListInstances returns list of instances that match the criteria.
	ListInstances(ctx context.Context, opts ...ctrlclient.ListOption) (*v1alpha1.InstanceList, error)
	// GetInstance returns instance that matches the criteria.
	GetInstance(ctx context.Context, key ctrlclient.ObjectKey) (*v1alpha1.Instance, error)
	// DeleteInstance deletes instance that matches the criteria.
	DeleteInstance(ctx context.Context, obj *v1alpha1.Instance) error
	// CreateInstance creates instance.
	CreateInstance(ctx context.Context, instance *v1alpha1.Instance) (*v1alpha1.Instance, error)
	// UpdateInstance updates instance.
	UpdateInstance(ctx context.Context, instance *v1alpha1.Instance) (*v1alpha1.Instance, error)
}
