// everest
// Copyright (C) 2023 Percona LLC
// Copyright (C) 2026 The OpenEverest Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package server

import (
	"net/http"
	"net/url"

	"github.com/labstack/echo/v4"
	"github.com/unrolled/secure"
	"github.com/unrolled/secure/cspbuilder"

	"github.com/openeverest/openeverest/v2/pkg/oidc"
)

const (
	CSPSelf           = "'self'"
	CSPNone           = "'none'"
	PermissionsPolicy = "accelerometer=(), autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(self), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(self), clipboard-write=(self), gamepad=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), unload=()"
)

func (e *EverestServer) securityHeaders() echo.MiddlewareFunc {
	oidcProvider := e.oidcProvider
	useTLS := e.config.TLSCertsPath != ""
	connectSrc := []string{CSPSelf}
	if oidcProvider != nil {
		issuer, _ := url.JoinPath(oidcProvider.Issuer, oidc.WellKnownPath)
		connectSrc = append(connectSrc, issuer)
		connectSrc = append(connectSrc, oidcProvider.TokenURL)
		if oidcProvider.OriginalIssuer != oidcProvider.Issuer {
			// It appears that original issuerUrl provided by user for OIDC configuration is not always
			// the same as the one fetched from the OIDC provider's .well-known/openid-configuration (Microsoft Entra case).
			// Need to add original issuer URL provided by user, otherwise there will be issues with browser login using SSO.
			origIssuer, _ := url.JoinPath(oidcProvider.OriginalIssuer, oidc.WellKnownPath)
			connectSrc = append(connectSrc, origIssuer)
		}
	}

	cspBuilder := cspbuilder.Builder{
		Directives: map[string][]string{
			cspbuilder.DefaultSrc: {CSPSelf},
			cspbuilder.FontSrc:    {CSPSelf, "data:"},
			cspbuilder.StyleSrc: {
				CSPSelf,
				// $NONCE will be replaced by the real nonce value
				// auto-generated by the secure middleware. This nonce will
				// be stored in the request's context and shall be embedded in
				// the index.html template.
				"$NONCE",
				// @emotion adds an extra inline style with the SHA256 hash of
				// an empty string, so we need to explicity allow it, see:
				// https://github.com/emotion-js/emotion/issues/2996
				"'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='",
			},
			cspbuilder.FormAction:     {CSPSelf},
			cspbuilder.BaseURI:        {CSPSelf},
			cspbuilder.ObjectSrc:      {CSPNone},
			cspbuilder.FrameAncestors: {CSPNone},
			cspbuilder.ConnectSrc:     connectSrc,
		},
	}

	opts := secure.Options{
		ContentTypeNosniff:            true,
		CrossOriginEmbedderPolicy:     "require-corp",
		CrossOriginOpenerPolicy:       "same-origin",
		CrossOriginResourcePolicy:     "same-origin",
		FrameDeny:                     true,
		PermissionsPolicy:             PermissionsPolicy,
		ReferrerPolicy:                "no-referrer",
		XPermittedCrossDomainPolicies: "none",
	}

	if useTLS {
		opts.SSLRedirect = true
		opts.STSIncludeSubdomains = true
		opts.STSSeconds = 31536000

		cspBuilder.Directives[cspbuilder.UpgradeInsecureRequests] = []string{}
	}
	opts.ContentSecurityPolicy = cspBuilder.MustBuild()

	secureMiddleware := secure.New(opts)

	return echo.WrapMiddleware(func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Cache-Control", "no-store, max-age=0")
			secureMiddleware.Handler(next).ServeHTTP(w, r)
		})
	})
}
