apiVersion: core.openeverest.io/v1alpha1
kind: Provider
metadata:
  name: dummy-provider
spec:
  componentTypes:
    dummy-engine:
      versions:
        - version: "1.0.0"
          image: "dummy-operator:1.0.0"
          default: true
  components:
    engine:
      type: dummy-engine
  topologies:
    standalone:
      components:
        engine: {}
  versions:
    - components:
        engine: "1.0.0"
      name: "1.0.0"
      default: true
